#!/usr/bin/env bash
set -euo pipefail

ROOT=${ROOT:-$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)}
cd "$ROOT"

PY=${PY:-/home/photogrammetry/miniconda3/envs/plmloc/bin/python}
if [[ ! -x "$PY" ]]; then
  PY=python
fi
export PYTHONPATH=${PYTHONPATH:-$ROOT}

DISK=${DISK:-/media/photogrammetry/A26C3DDF6C3DAF431}
DATA=${DATA:-$DISK/datasets}
RUNS=${RUNS:-$DISK/plm-match-runs/adaptive_cover_visual}
SUB=${SUB:-$DISK/plm-match-runs/visual_localization_submissions/adaptive_cover}

AACHEN_SRC=${AACHEN_SRC:-$DATA/aachen_v1_1}
OLD_AACHEN=${OLD_AACHEN:-$DISK/plm-match-runs/aachen_submission_plmloc}
AACHEN_FULL=${AACHEN_FULL:-$RUNS/inputs/aachen_v1_1_full1015}

FEATURE=${FEATURE:-aliked}
AACHEN_TOPK=${AACHEN_TOPK:-10}
AACHEN_PLM_RETRIEVAL_METHOD=${AACHEN_PLM_RETRIEVAL_METHOD:-mixvpr}
AACHEN_PLM_RETRIEVAL_FILE=${AACHEN_PLM_RETRIEVAL_FILE:-$OLD_AACHEN/retrieval_mixvpr/pairs-loo-mixvpr${AACHEN_TOPK}.txt}
AACHEN_RUN_TAG=${AACHEN_RUN_TAG:-}
AACHEN_ATTACH_TAG=${AACHEN_ATTACH_TAG:-}
AACHEN_LOCAL_MAX_KEYPOINTS=${AACHEN_LOCAL_MAX_KEYPOINTS:-4096}
AACHEN_LOCAL_RESIZE_MAX=${AACHEN_LOCAL_RESIZE_MAX:-1600}
ATTACH_RADIUS_PX=${ATTACH_RADIUS_PX:-3}
MIN_COLMAP_TRACK_LEN=${MIN_COLMAP_TRACK_LEN:-3}
MAX_COLMAP_POINT_ERROR=${MAX_COLMAP_POINT_ERROR:-4.0}
POINT_MEMORY_OBS_SELECT=${POINT_MEMORY_OBS_SELECT:-adaptive_cover}
POINT_MEMORY_OBS_TAG=${POINT_MEMORY_OBS_TAG:-$POINT_MEMORY_OBS_SELECT}
POINT_MEMORY_MAX_OBS=${POINT_MEMORY_MAX_OBS:-0}
POINT_MEMORY_ADAPTIVE_K_MIN=${POINT_MEMORY_ADAPTIVE_K_MIN:-1}
POINT_MEMORY_ADAPTIVE_K_MAX=${POINT_MEMORY_ADAPTIVE_K_MAX:-32}
POINT_MEMORY_ADAPTIVE_MIN_GAIN=${POINT_MEMORY_ADAPTIVE_MIN_GAIN:-0.005}
POINT_MEMORY_ADAPTIVE_SIGMA_ATTACH=${POINT_MEMORY_ADAPTIVE_SIGMA_ATTACH:-2.0}
POINT_MEMORY_ADAPTIVE_SIGMA_REPROJ=${POINT_MEMORY_ADAPTIVE_SIGMA_REPROJ:-4.0}
POINT_MEMORY_ADAPTIVE_VIEW_WEIGHT=${POINT_MEMORY_ADAPTIVE_VIEW_WEIGHT:-0.0}
POINT_MEMORY_ADAPTIVE_S_MIN=${POINT_MEMORY_ADAPTIVE_S_MIN:-0.80}
POINT_MEMORY_ADAPTIVE_GATE_FRAC=${POINT_MEMORY_ADAPTIVE_GATE_FRAC:-0.30}
MIXVPR_DEVICE=${MIXVPR_DEVICE:-cuda}
PNP_FIRST_THRESH=${PNP_FIRST_THRESH:-12.0}
PNP_REFINE_THRESH=${PNP_REFINE_THRESH:-$PNP_FIRST_THRESH}
MIN_FINAL_INLIERS=${MIN_FINAL_INLIERS:-12}
POSE_GUIDED=${POSE_GUIDED:-0}
POSE_GUIDED_RADIUS_PX=${POSE_GUIDED_RADIUS_PX:-10.0}
POSE_GUIDED_SCORE_THRESH=${POSE_GUIDED_SCORE_THRESH:-0.1}
POSE_GUIDED_REPROJ_PENALTY=${POSE_GUIDED_REPROJ_PENALTY:-0.02}
POSE_GUIDED_MAX_DESCS_PER_POINT=${POSE_GUIDED_MAX_DESCS_PER_POINT:-8}
MIN_POSE_GUIDED_INLIERS=${MIN_POSE_GUIDED_INLIERS:-12}
AACHEN_MAX_QUERIES=${AACHEN_MAX_QUERIES:-}
REBUILD_ATTACHMENT=${REBUILD_ATTACHMENT:-0}

tag_number() {
  local value="$1"
  value="${value%.0}"
  value="${value//./p}"
  printf '%s' "$value"
}

GAIN_TAG=${POINT_MEMORY_ADAPTIVE_MIN_GAIN/./}
PNP_TAG_DEFAULT="pnp$(tag_number "$PNP_FIRST_THRESH")"
if [[ "$(tag_number "$PNP_REFINE_THRESH")" != "$(tag_number "$PNP_FIRST_THRESH")" ]]; then
  PNP_TAG_DEFAULT="${PNP_TAG_DEFAULT}_ref$(tag_number "$PNP_REFINE_THRESH")"
fi
PNP_TAG_DEFAULT="${PNP_TAG_DEFAULT}_min${MIN_FINAL_INLIERS}"
PNP_TAG=${PNP_TAG:-$PNP_TAG_DEFAULT}
POSE_TAG=""
if [[ "$POSE_GUIDED" == "1" || "$POSE_GUIDED" == "true" || "$POSE_GUIDED" == "TRUE" ]]; then
  POSE_TAG="_poseguided"
  if [[ "$MIN_POSE_GUIDED_INLIERS" != "$MIN_FINAL_INLIERS" ]]; then
    POSE_TAG="${POSE_TAG}_pgmin${MIN_POSE_GUIDED_INLIERS}"
  fi
fi
RETRIEVAL_TAG=${AACHEN_PLM_RETRIEVAL_METHOD}${AACHEN_TOPK}
MAXQ_TAG=""
if [[ -n "$AACHEN_MAX_QUERIES" ]]; then
  MAXQ_TAG="_maxq${AACHEN_MAX_QUERIES}"
fi
case "$POINT_MEMORY_OBS_SELECT" in
  adaptive_cover|adaptive_cover_farthest|adaptive_cover_v2)
    SELECTOR_TAG="${POINT_MEMORY_OBS_TAG}_k${POINT_MEMORY_ADAPTIVE_K_MIN}_${POINT_MEMORY_ADAPTIVE_K_MAX}_gain${GAIN_TAG}"
    ;;
  *)
    SELECTOR_TAG="${POINT_MEMORY_OBS_TAG}_obs${POINT_MEMORY_MAX_OBS}"
    ;;
esac
METHOD_TAG="${FEATURE}_${RETRIEVAL_TAG}_${SELECTOR_TAG}_${PNP_TAG}${POSE_TAG}${MAXQ_TAG}"
RESULT_NAME=${RESULT_NAME:-plmloc_${METHOD_TAG}}

for required in \
  "$AACHEN_SRC/images_upright" \
  "$AACHEN_SRC/3D-models/aachen_v_1_1" \
  "$OLD_AACHEN/split/query_list_with_intrinsics.txt" \
  "$AACHEN_PLM_RETRIEVAL_FILE"; do
  if [[ ! -e "$required" ]]; then
    echo "Missing required input: $required" >&2
    exit 2
  fi
done

mkdir -p "$AACHEN_FULL/queries" "$RUNS" "$SUB"
ln -sfn "$AACHEN_SRC/images_upright" "$AACHEN_FULL/images_upright"
ln -sfn "$AACHEN_SRC/3D-models" "$AACHEN_FULL/3D-models"

awk '$1 ~ /^query\/day\//' "$OLD_AACHEN/split/query_list_with_intrinsics.txt" \
  > "$AACHEN_FULL/day_time_queries_with_intrinsics.txt"
awk '$1 ~ /^query\/night\//' "$OLD_AACHEN/split/query_list_with_intrinsics.txt" \
  > "$AACHEN_FULL/queries/night_time_queries_with_intrinsics.txt"

PY="$PY" OUTPUT_ROOT="$RUNS" AACHEN_ROOT="$AACHEN_FULL" \
RUN_AACHEN=1 RUN_ROBOTCAR=0 RUN_CMU=0 \
FEATURE="$FEATURE" AACHEN_TOPK="$AACHEN_TOPK" MIXVPR_DEVICE="$MIXVPR_DEVICE" \
AACHEN_PLM_RETRIEVAL_METHOD="$AACHEN_PLM_RETRIEVAL_METHOD" \
AACHEN_PLM_RETRIEVAL_FILE="$AACHEN_PLM_RETRIEVAL_FILE" \
AACHEN_HLOC_RETRIEVAL_FILE="$AACHEN_PLM_RETRIEVAL_FILE" \
AACHEN_RUN_TAG="$AACHEN_RUN_TAG" \
AACHEN_ATTACH_TAG="$AACHEN_ATTACH_TAG" \
AACHEN_LOCAL_MAX_KEYPOINTS="$AACHEN_LOCAL_MAX_KEYPOINTS" \
AACHEN_LOCAL_RESIZE_MAX="$AACHEN_LOCAL_RESIZE_MAX" \
ATTACH_RADIUS_PX="$ATTACH_RADIUS_PX" \
MIN_COLMAP_TRACK_LEN="$MIN_COLMAP_TRACK_LEN" \
MAX_COLMAP_POINT_ERROR="$MAX_COLMAP_POINT_ERROR" \
POINT_MEMORY_OBS_SELECT="$POINT_MEMORY_OBS_SELECT" \
POINT_MEMORY_MAX_OBS="$POINT_MEMORY_MAX_OBS" \
POINT_MEMORY_ADAPTIVE_K_MIN="$POINT_MEMORY_ADAPTIVE_K_MIN" \
POINT_MEMORY_ADAPTIVE_K_MAX="$POINT_MEMORY_ADAPTIVE_K_MAX" \
POINT_MEMORY_ADAPTIVE_MIN_GAIN="$POINT_MEMORY_ADAPTIVE_MIN_GAIN" \
POINT_MEMORY_ADAPTIVE_SIGMA_ATTACH="$POINT_MEMORY_ADAPTIVE_SIGMA_ATTACH" \
POINT_MEMORY_ADAPTIVE_SIGMA_REPROJ="$POINT_MEMORY_ADAPTIVE_SIGMA_REPROJ" \
POINT_MEMORY_ADAPTIVE_VIEW_WEIGHT="$POINT_MEMORY_ADAPTIVE_VIEW_WEIGHT" \
POINT_MEMORY_ADAPTIVE_S_MIN="$POINT_MEMORY_ADAPTIVE_S_MIN" \
POINT_MEMORY_ADAPTIVE_GATE_FRAC="$POINT_MEMORY_ADAPTIVE_GATE_FRAC" \
PNP_FIRST_THRESH="$PNP_FIRST_THRESH" \
PNP_REFINE_THRESH="$PNP_REFINE_THRESH" \
MIN_FINAL_INLIERS="$MIN_FINAL_INLIERS" \
POSE_GUIDED="$POSE_GUIDED" \
POSE_GUIDED_RADIUS_PX="$POSE_GUIDED_RADIUS_PX" \
POSE_GUIDED_SCORE_THRESH="$POSE_GUIDED_SCORE_THRESH" \
POSE_GUIDED_REPROJ_PENALTY="$POSE_GUIDED_REPROJ_PENALTY" \
POSE_GUIDED_MAX_DESCS_PER_POINT="$POSE_GUIDED_MAX_DESCS_PER_POINT" \
MIN_POSE_GUIDED_INLIERS="$MIN_POSE_GUIDED_INLIERS" \
AACHEN_MAX_QUERIES="$AACHEN_MAX_QUERIES" \
REBUILD_ATTACHMENT="$REBUILD_ATTACHMENT" \
RESULT_NAME="$RESULT_NAME" \
bash scripts/run_large_scale_adaptive_cover.sh

AACHEN_PRED="$RUNS/aachen_day_night/results/${RESULT_NAME}_day_night_hloc_results.txt"
AACHEN_SUB="$SUB/Aachen_v1_1_eval_PLMLoc_${METHOD_TAG}.txt"

if [[ ! -f "$AACHEN_PRED" ]]; then
  echo "Missing prediction file: $AACHEN_PRED" >&2
  exit 2
fi

awk '{name=$1; sub(/^.*\//,"",name); printf "%s", name; for(i=2;i<=NF;i++) printf " %s",$i; printf "\n"}' \
  "$AACHEN_PRED" > "$AACHEN_SUB"

echo "Aachen prediction file: $AACHEN_PRED"
echo "Aachen submission txt: $AACHEN_SUB"
wc -l "$AACHEN_SUB"
